CC = gcc

# The executable
TARGET = assn2

# Source file
SRC = main.c

# Build target
all: $(TARGET)

# Building executable
$(TARGET): $(SRC)
	$(CC) -g -o $(TARGET) $(SRC)

# Cleaning compiled files
clean:
	rm -f $(TARGET)
